<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
    <nav class="navbar">
        <ul class="navbar-nav">
            <li class="nav-item"><?php echo $this->tag->linkTo(["customers", "Go Back"]) ?></li>
        </ul>
    </nav>
</div>

<div class="row page-header">
    <h1>
        Create customers
    </h1>
</div>

<?php echo $this->getContent(); ?>

<div class="row justify-content-center">
<?php
    echo $this->tag->form(
        [
            "customers/create",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldName" class="col-sm-2 control-label">Name</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["name", "size" => 30, "class" => "form-control", "id" => "fieldName"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldPhoneNumber" class="col-sm-2 control-label">Phone Number</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["phone_number", "size" => 30, "class" => "form-control", "id" => "fieldPhoneNumber"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldBalance" class="col-sm-2 control-label">Balance</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["balance", "size" => 30, "class" => "form-control", "id" => "fieldBalance"]) ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Save", "class" => "btn btn-primary"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
</div>
