<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
    <nav class="navbar">
        <ul class="navbar-nav">
            <li class="nav-item"><?php echo $this->tag->linkTo(["orders", "Go Back"]) ?></li>
        </ul>
    </nav>
</div>

<div class="row page-header">
    <h1>
        Create orders
    </h1>
</div>

<?php echo $this->getContent(); ?>

<div class="row justify-content-center">
<?php
    echo $this->tag->form(
        [
            "orders/create",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldCustomerId" class="col-sm-2 control-label">Customer</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["customer_id", "type" => "number", "class" => "form-control", "id" => "fieldCustomerId"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldDueDate" class="col-sm-2 control-label">Due Date</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["due_date", "type" => "date", "class" => "form-control", "id" => "fieldDueDate"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldDetails" class="col-sm-2 control-label">Details</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textArea(["details", "cols" => 30, "rows" => 4, "class" => "form-control", "id" => "fieldDetails"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldStatus" class="col-sm-2 control-label">Status</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["status", "size" => 30, "class" => "form-control", "id" => "fieldStatus"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldCost" class="col-sm-2 control-label">Cost</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["cost", "size" => 30, "class" => "form-control", "id" => "fieldCost"]) ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Save", "class" => "btn btn-primary"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>

</div>
