<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
    <nav class="navbar">
        <ul class="navbar-nav">
            <li class="nav-item"><?php echo $this->tag->linkTo(["orders/index", "Go Back"]); ?></li>
            <li class="nav-item"><?php echo $this->tag->linkTo(["orders/new", "Create "]); ?></li>
        </ul>
    </nav>
</div>

<div class="row page-header">
    <h1>Search result</h1>
</div>

<?php echo $this->getContent(); ?>

<div class="row justify-content-center">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Order</th>
            <th>Customer</th>
            <th>Due Date</th>
            <th>Details</th>
            <th>Status</th>
            <th>Cost</th>

                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $order): ?>
            <tr>
                <td><?php echo $order->order_id ?></td>
            <td><?php echo $order->customer_id ?></td>
            <td><?php echo $order->due_date ?></td>
            <td><?php echo $order->details ?></td>
            <td><?php echo $order->status ?></td>
            <td><?php echo $order->cost ?></td>

                <td><?php echo $this->tag->linkTo(["orders/edit/" . $order->order_id, "Edit"]); ?></td>
                <td><?php echo $this->tag->linkTo(["orders/delete/" . $order->order_id, "Delete"]); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="row">
    <div class="col-sm-1">
        <p class="" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, "/", $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo(["orders/search", "First", "class" => "page-link"]) ?></li>
                <li><?php echo $this->tag->linkTo(["orders/search?page=" . $page->before, "Previous", "class" => "page-link"]) ?></li>
                <li><?php echo $this->tag->linkTo(["orders/search?page=" . $page->next, "Next", "class" => "page-link"]) ?></li>
                <li><?php echo $this->tag->linkTo(["orders/search?page=" . $page->last, "Last", "class" => "page-link"]) ?></li>
            </ul>
        </nav>
    </div>
</div>
